function(jn_quote output value)
    string(REPLACE "\\" "\\\\" escaped "${value}")
    string(REPLACE "\"" "\\\"" escaped "${escaped}")
    string(REPLACE "\n" "\\n" escaped "${escaped}")
    string(REPLACE "\r" "\\r" escaped "${escaped}")
    set(${output} "\"${escaped}\"" PARENT_SCOPE)
endfunction()
function(jn_run)
    execute_process(COMMAND ${ARGV} RESULT_VARIABLE code ERROR_VARIABLE error)
    if(NOT code EQUAL 0)
        message(FATAL_ERROR "Diagnostic artifact command failed: ${error}")
    endif()
endfunction()
file(READ "${JN_BINARY}/jnative_identity.hpp" identity)
string(REGEX MATCH "\"([0-9a-f]+)\"" match "${identity}")
set(id "${CMAKE_MATCH_1}")
string(LENGTH "${id}" id_length)
if(NOT id_length EQUAL 32)
    message(FATAL_ERROR "Missing link identity")
endif()
set(bundle "${JN_PROJECT}/diagnostics/${id}")
if(EXISTS "${bundle}/manifest.json")
    message(FATAL_ERROR "Immutable diagnostic bundle already exists: ${bundle}")
endif()
file(MAKE_DIRECTORY "${bundle}/images" "${bundle}/linked" "${bundle}/symbols")
set(mode "${JN_SYMBOLS}")
if(mode STREQUAL "AUTO")
    if(JN_CONFIG STREQUAL "Debug")
        set(mode EMBEDDED)
    else()
        set(mode SEPARATE)
    endif()
endif()
get_filename_component(exe_name "${JN_EXE}" NAME)
get_filename_component(release "${JN_EXE}" DIRECTORY)
set(artifacts "${JN_EXE}")
set(linked_images "${JN_EXE}")
if(JN_HELPER)
    get_filename_component(helper_name "${JN_HELPER}" NAME)
    set(JN_HELPER_DIST "${release}/${helper_name}")
    configure_file("${JN_HELPER}" "${JN_HELPER_DIST}" COPYONLY)
    list(APPEND artifacts "${JN_HELPER_DIST}")
    list(APPEND linked_images "${JN_HELPER}")
endif()
include("${CMAKE_CURRENT_LIST_DIR}/jn_dependencies.cmake")
jn_copy_runtime_dependencies("${linked_images}" EXECUTABLE "${JN_SYSTEM}" "${JN_OBJDUMP}" dependencies)
list(APPEND artifacts ${dependencies})
list(REMOVE_DUPLICATES artifacts)
set(modules "[]")
set(index 0)
foreach(image IN LISTS artifacts)
    get_filename_component(name "${image}" NAME)
    configure_file("${image}" "${bundle}/linked/${name}" COPYONLY)
    set(symbol "linked/${name}")
    if((image STREQUAL JN_EXE OR image STREQUAL JN_HELPER_DIST) AND mode STREQUAL "SEPARATE")
        if(NOT JN_OBJCOPY OR NOT JN_STRIP)
            message(FATAL_ERROR "Separate symbols require objcopy and strip from the target toolchain")
        endif()
        set(symbol "symbols/${name}.debug")
        jn_run("${JN_OBJCOPY}" --only-keep-debug "${image}" "${bundle}/${symbol}")
        jn_run("${JN_STRIP}" --strip-debug "${image}")
        jn_run("${JN_OBJCOPY}" "--add-gnu-debuglink=${bundle}/${symbol}" "${image}")
    endif()
    if(JN_FINALIZE AND (image STREQUAL JN_EXE OR image STREQUAL JN_HELPER_DIST))
        jn_run(${JN_FINALIZE} "${image}")
    endif()
    configure_file("${image}" "${bundle}/images/${name}" COPYONLY)
    file(SHA256 "${bundle}/images/${name}" hash)
    set(module "{}")
    jn_quote(value "${name}")
    string(JSON module SET "${module}" name "${value}")
    string(JSON module SET "${module}" sha256 "\"${hash}\"")
    jn_quote(value "images/${name}")
    string(JSON module SET "${module}" image "${value}")
    jn_quote(value "${symbol}")
    string(JSON module SET "${module}" symbols "${value}")
    if(mode STREQUAL "NONE")
        string(JSON module SET "${module}" symbolStatus "\"unavailable\"")
    else()
        string(JSON module SET "${module}" symbolStatus "\"inspect-with-symbolizer\"")
    endif()
    string(JSON modules SET "${modules}" ${index} "${module}")
    math(EXPR index "${index}+1")
endforeach()
set(staging "${JN_BINARY}/a/${id}")
file(READ "${JN_BINARY}/jnative-inputs.json" inputs)
string(JSON input_count LENGTH "${inputs}")
math(EXPR input_last "${input_count}-1")
foreach(index RANGE ${input_last})
    string(JSON source MEMBER "${inputs}" ${index})
    string(JSON expected GET "${inputs}" "${source}")
    file(SHA256 "${source}" actual)
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "Source changed during compilation; rebuild before archiving: ${source}")
    endif()
endforeach()
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cf "${bundle}/sources.zip" --format=zip .
    WORKING_DIRECTORY "${staging}" RESULT_VARIABLE zipped)
if(NOT zipped EQUAL 0)
    message(FATAL_ERROR "Cannot archive compiled sources")
endif()
file(GLOB_RECURSE source_files LIST_DIRECTORIES FALSE RELATIVE "${staging}" "${staging}/*")
set(source_hashes "{}")
foreach(relative IN LISTS source_files)
    file(SHA256 "${staging}/${relative}" hash)
    string(JSON source_hashes SET "${source_hashes}" "${relative}" "\"${hash}\"")
endforeach()
file(WRITE "${bundle}/source-hashes.json" "${source_hashes}\n")
if(EXISTS "${JN_SOURCES}/source-map.json")
    configure_file("${staging}/src/source-map.json" "${bundle}/source-map.json" COPYONLY)
endif()
set(manifest "{\"schema\":1}")
string(JSON manifest SET "${manifest}" buildId "\"${id}\"")
jn_quote(value "${exe_name}")
string(JSON manifest SET "${manifest}" executable "${value}")
foreach(key IN ITEMS JN_CONFIG JN_COMPILER JN_FLAGS JN_SYSTEM JN_DEFINITIONS JN_LINK_FLAGS JN_CMAKE mode)
    jn_quote(value "${${key}}")
    string(JSON manifest SET "${manifest}" "${key}" "${value}")
endforeach()
string(JSON manifest SET "${manifest}" modules "${modules}")
jn_quote(value "${unresolved}")
string(JSON manifest SET "${manifest}" unresolvedDependencies "${value}")
file(GLOB_RECURSE contents LIST_DIRECTORIES FALSE RELATIVE "${bundle}" "${bundle}/*")
set(hashes "{}")
foreach(relative IN LISTS contents)
    file(SHA256 "${bundle}/${relative}" hash)
    string(JSON hashes SET "${hashes}" "${relative}" "\"${hash}\"")
endforeach()
string(JSON manifest SET "${manifest}" files "${hashes}")
file(WRITE "${bundle}/manifest.json" "${manifest}\n")
file(WRITE "${JN_PROJECT}/diagnostics/latest-${JN_CONFIG}.txt" "${id}\n")
message(STATUS "Diagnostic bundle: ${bundle} (copy to a private archive before cleaning)")
