# Hash inputs before compilation to reject source edits made during a build.
string(RANDOM LENGTH 32 ALPHABET 0123456789abcdef id)
file(WRITE "${OUTPUT}" "#pragma once\n#define JNATIVE_BUILD_ID \"${id}\"\n")
get_filename_component(binary "${OUTPUT}" DIRECTORY)
set(staging "${binary}/a/${id}")
file(MAKE_DIRECTORY "${staging}")
set(inputs "{}")
function(jn_snapshot directory prefix)
    file(GLOB_RECURSE entries LIST_DIRECTORIES FALSE RELATIVE "${directory}" "${directory}/*")
    foreach(relative IN LISTS entries)
        set(source "${directory}/${relative}")
        set(target "${staging}/${prefix}${relative}")
        string(LENGTH "${target}" length)
        if(length GREATER 220)
            message(FATAL_ERROR "JN4010 Archive source path exceeds the portable 220-character budget: ${target}. Shorten the owning build directory.")
        endif()
        get_filename_component(parent "${target}" DIRECTORY)
        file(MAKE_DIRECTORY "${parent}")
        configure_file("${source}" "${target}" COPYONLY)
        file(SHA256 "${target}" hash)
        string(JSON inputs SET "${inputs}" "${source}" "\"${hash}\"")
    endforeach()
    set(inputs "${inputs}" PARENT_SCOPE)
endfunction()
jn_snapshot("${SOURCES}" "src/")
jn_snapshot("${PROJECT}/runtime" "runtime/")
if(EXISTS "${PROJECT}/user")
    jn_snapshot("${PROJECT}/user" "user/")
endif()
foreach(name IN ITEMS CMakeLists.txt jnative-project.properties)
    configure_file("${PROJECT}/${name}" "${staging}/${name}" COPYONLY)
    file(SHA256 "${staging}/${name}" hash)
    string(JSON inputs SET "${inputs}" "${PROJECT}/${name}" "\"${hash}\"")
endforeach()
# Retain additional project-owned C/C++ headers, sources, and CMake includes.
file(GLOB_RECURSE project_inputs LIST_DIRECTORIES FALSE RELATIVE "${PROJECT}"
    "${PROJECT}/*.h" "${PROJECT}/*.hpp" "${PROJECT}/*.hh" "${PROJECT}/*.inc" "${PROJECT}/*.inl"
    "${PROJECT}/*.c" "${PROJECT}/*.cc" "${PROJECT}/*.cpp" "${PROJECT}/*.cxx" "${PROJECT}/*.cmake" "${PROJECT}/CMakeLists.txt")
foreach(name IN LISTS project_inputs)
    if(name MATCHES "^(b|build|debug|release|diagnostics|runtime|user)/" OR name STREQUAL "CMakeLists.txt")
        continue()
    endif()
    set(source "${PROJECT}/${name}")
    cmake_path(IS_PREFIX SOURCES "${source}" NORMALIZE in_sources)
    cmake_path(IS_PREFIX binary "${source}" NORMALIZE in_binary)
    if(NOT in_sources AND NOT in_binary)
        list(APPEND EXTRA "${name}")
    endif()
endforeach()
list(REMOVE_DUPLICATES EXTRA)
foreach(name IN LISTS EXTRA)
    cmake_path(ABSOLUTE_PATH name BASE_DIRECTORY "${PROJECT}" NORMALIZE OUTPUT_VARIABLE source)
    cmake_path(IS_PREFIX PROJECT "${source}" NORMALIZE inside)
    if(NOT inside OR IS_DIRECTORY "${source}")
        message(FATAL_ERROR "JNATIVE_ARCHIVE_INPUTS requires project-relative files: ${name}")
    endif()
    configure_file("${source}" "${staging}/${name}" COPYONLY)
    file(SHA256 "${staging}/${name}" hash)
    string(JSON inputs SET "${inputs}" "${source}" "\"${hash}\"")
endforeach()
file(MAKE_DIRECTORY "${staging}/build-info")
configure_file("${OUTPUT}" "${staging}/build-info/jnative_identity.hpp" COPYONLY)
file(WRITE "${binary}/jnative-inputs.json" "${inputs}\n")
