# A toolchain may provide an implementation of jn_platform.hpp instead of either
# desktop provider. Services are explicit so missing requirements fail at configure.
set(JNATIVE_PLATFORM_SOURCES "" CACHE STRING "External platform implementation sources")
set(JNATIVE_PLATFORM_INCLUDES "" CACHE STRING "External platform include directories")
set(JNATIVE_PLATFORM_LIBRARIES "" CACHE STRING "External platform libraries")
set(JNATIVE_PLATFORM_SERVICES "" CACHE STRING "Services implemented by the external platform")
set(_jn_platform_dir "${CMAKE_CURRENT_LIST_DIR}")
set(_jn_required_services threads synchronization tls allocation floating files clocks output)
if(JNATIVE_PLATFORM_SOURCES)
    set(_jn_platform_sources ${JNATIVE_PLATFORM_SOURCES})
    set(_jn_platform_name external)
    set(_jn_services ${JNATIVE_PLATFORM_SERVICES})
    foreach(_service IN LISTS _jn_required_services)
        if(NOT _service IN_LIST JNATIVE_PLATFORM_SERVICES)
            message(FATAL_ERROR "jNative requires platform service: ${_service}")
        endif()
    endforeach()
elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
    set(_jn_platform_sources "${_jn_platform_dir}/jn_platform_windows.cpp")
    set(_jn_platform_name windows)
    set(_jn_services ${_jn_required_services} process-exit console native-traces crash-reports try-lock)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(_jn_platform_sources "${_jn_platform_dir}/jn_platform_linux.cpp")
    set(_jn_platform_name linux)
    set(_jn_services ${_jn_required_services} process-exit console native-traces crash-reports try-lock)
else()
    message(FATAL_ERROR "No jNative platform provider for ${CMAKE_SYSTEM_NAME}. Set JNATIVE_PLATFORM_SOURCES and JNATIVE_PLATFORM_SERVICES in your toolchain.")
endif()
function(jnative_require_service service feature)
    if(NOT service IN_LIST _jn_services)
        message(FATAL_ERROR "${feature} requires unavailable platform service: ${service}. Disable this option or supply a provider declaring the service in JNATIVE_PLATFORM_SERVICES.")
    endif()
endfunction()
add_library(jnative_platform STATIC ${_jn_platform_sources} "${_jn_platform_dir}/jn_paths.cpp" "${_jn_platform_dir}/jn_output.cpp")
if("try-lock" IN_LIST _jn_services)
    target_compile_definitions(jnative_platform PUBLIC JNATIVE_PLATFORM_TRY_LOCK=1)
endif()
if(_jn_platform_name STREQUAL "windows" AND MSVC AND CMAKE_SIZEOF_VOID_P EQUAL 8
        AND CMAKE_CXX_COMPILER_ARCHITECTURE_ID STREQUAL "x64")
    enable_language(ASM_MASM)
    target_sources(jnative_platform PRIVATE "${_jn_platform_dir}/jn_floating_x64.asm")
    target_compile_definitions(jnative_platform PRIVATE JNATIVE_X64_FLOATING=1)
endif()
set_target_properties(jnative_platform PROPERTIES POSITION_INDEPENDENT_CODE ON)
target_include_directories(jnative_platform PUBLIC "${_jn_platform_dir}" ${JNATIVE_PLATFORM_INCLUDES})
target_link_libraries(jnative_platform PUBLIC ${JNATIVE_PLATFORM_LIBRARIES})
if(_jn_platform_name STREQUAL "linux")
    find_package(Threads REQUIRED)
    target_link_libraries(jnative_platform PUBLIC Threads::Threads)
endif()
list(JOIN _jn_services "," _jn_available_services)
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/jnative-platform.properties"
    "provider=${_jn_platform_name}\nrequired=threads,synchronization,tls,allocation,floating,files,clocks,output\noptional=process-exit,console,native-traces,crash-reports,try-lock\navailable=${_jn_available_services}\n")
