# Included from a generated project's CMakeLists, including via add_subdirectory.
if(NOT DEFINED JNATIVE_OUTPUT_KIND)
    set(JNATIVE_OUTPUT_KIND EXECUTABLE CACHE STRING "EXECUTABLE, STATIC_LIBRARY or SHARED_LIBRARY")
endif()
if(NOT JNATIVE_OUTPUT_KIND MATCHES "^(EXECUTABLE|STATIC_LIBRARY|SHARED_LIBRARY)$")
    message(FATAL_ERROR "Unsupported JNATIVE_OUTPUT_KIND: ${JNATIVE_OUTPUT_KIND}")
endif()
if(TARGET jnative_runtime)
    message(FATAL_ERROR "A jNative application/runtime is already present in this CMake build. Use one generated application with multiple exported entry points.")
endif()
if(NOT CMAKE_CONFIGURATION_TYPES AND NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE Debug CACHE STRING "Native build configuration" FORCE)
endif()
set(_jn_runtime "${CMAKE_CURRENT_LIST_DIR}")
set(CMAKE_OBJECT_PATH_MAX 240)
set(JNATIVE_RUNTIME_LIBRARY_DIRECTORIES "" CACHE STRING "Additional target runtime library search directories")
include("${CMAKE_CURRENT_SOURCE_DIR}/jnative-sources.cmake")
include("${_jn_runtime}/jn_features.cmake")
include("${_jn_runtime}/jn_platform.cmake")
add_library(jnative_runtime STATIC ${JNATIVE_RUNTIME_SOURCES})
set_target_properties(jnative_runtime PROPERTIES POSITION_INDEPENDENT_CODE ON)
target_include_directories(jnative_runtime PUBLIC "${_jn_runtime}")
target_link_libraries(jnative_runtime PUBLIC jnative_features jnative_platform)
add_library(jnative_classes OBJECT ${JNATIVE_APPLICATION_SOURCES} ${JNATIVE_NATIVE_SOURCES})
set_target_properties(jnative_classes PROPERTIES POSITION_INDEPENDENT_CODE ON)
target_include_directories(jnative_classes PUBLIC "${JNATIVE_SOURCE_DIRECTORY}" "${CMAKE_CURRENT_SOURCE_DIR}/user")
target_link_libraries(jnative_classes PUBLIC jnative_runtime)
option(JNATIVE_PRECOMPILE_HEADERS "Reuse generated declarations when compiling application classes" ON)
if(JNATIVE_PRECOMPILE_HEADERS)
    target_precompile_headers(jnative_classes PRIVATE
        "$<$<COMPILE_LANGUAGE:CXX>:${JNATIVE_SOURCE_DIRECTORY}/application.hpp>"
        "$<$<COMPILE_LANGUAGE:CXX>:${JNATIVE_SOURCE_DIRECTORY}/java_api.hpp>")
endif()
if(MSVC)
    set(JNATIVE_MSVC_COMPILE_JOBS 2 CACHE STRING "Concurrent MSVC compilation jobs per application target")
    target_compile_options(jnative_classes PRIVATE /MP${JNATIVE_MSVC_COMPILE_JOBS} /bigobj)
endif()
set(_jn_compiled_targets jnative_runtime jnative_classes jnative_platform)
if(JNATIVE_OUTPUT_KIND STREQUAL "EXECUTABLE")
    jnative_require_service(process-exit "The standalone launcher")
    add_library(jnative_launcher OBJECT "${JNATIVE_SOURCE_DIRECTORY}/launcher.cpp" "${_jn_runtime}/jn_console.cpp")
    target_include_directories(jnative_launcher PRIVATE "${JNATIVE_SOURCE_DIRECTORY}" "${CMAKE_CURRENT_SOURCE_DIR}/user")
    target_link_libraries(jnative_launcher PRIVATE jnative_runtime)
    list(APPEND _jn_compiled_targets jnative_launcher)
    add_executable(jnative_app $<TARGET_OBJECTS:jnative_classes> $<TARGET_OBJECTS:jnative_launcher>)
    set_target_properties(jnative_app PROPERTIES WIN32_EXECUTABLE FALSE)
    if(MINGW)
        target_link_options(jnative_app PRIVATE -municode)
    endif()
    option(JNATIVE_PAUSE_ON_EXIT "Wait for input before exiting an interactive console" ${JNATIVE_DEFAULT_PAUSE})
    if(JNATIVE_PAUSE_ON_EXIT)
        jnative_require_service(console JNATIVE_PAUSE_ON_EXIT)
    endif()
    target_compile_definitions(jnative_launcher PRIVATE JNATIVE_PAUSE_ON_EXIT=$<BOOL:${JNATIVE_PAUSE_ON_EXIT}>)
else()
    if(JNATIVE_OUTPUT_KIND STREQUAL "STATIC_LIBRARY")
        add_library(jnative_app STATIC $<TARGET_OBJECTS:jnative_classes>)
        set_target_properties(jnative_app PROPERTIES POSITION_INDEPENDENT_CODE ON)
    else()
        add_library(jnative_app SHARED $<TARGET_OBJECTS:jnative_classes>)
        set_target_properties(jnative_app PROPERTIES WINDOWS_EXPORT_ALL_SYMBOLS ON)
        target_compile_definitions(jnative_runtime PRIVATE JNATIVE_BUILD_SHARED=1)
        target_compile_definitions(jnative_classes PRIVATE JNATIVE_BUILD_SHARED=1)
    endif()
    # The host owns fatal handlers and final-image symbol archival. Explicit
    # native exception tracing is still available on supported desktop targets.
    set(JNATIVE_DEFAULT_NATIVE_TRACES 0)
    set(JNATIVE_DEFAULT_CRASH_REPORTS OFF)
    set(JNATIVE_DEFAULT_SYMBOLS NONE)
endif()
list(APPEND _jn_compiled_targets jnative_app)
# Keep separate readable class files while allowing the release compiler to
# inline small methods and runtime helpers across those translation units.
set(JNATIVE_IPO AUTO CACHE STRING "Release interprocedural optimization: AUTO, ON or OFF")
set_property(CACHE JNATIVE_IPO PROPERTY STRINGS AUTO ON OFF)
if(NOT JNATIVE_IPO MATCHES "^(AUTO|ON|OFF)$")
    message(FATAL_ERROR "JNATIVE_IPO must be AUTO, ON or OFF")
endif()
set(_jn_ipo_supported FALSE)
if(NOT JNATIVE_IPO STREQUAL "OFF")
    include(CheckIPOSupported)
    if(POLICY CMP0138)
        cmake_policy(SET CMP0138 NEW)
    endif()
    check_ipo_supported(RESULT _jn_ipo_supported OUTPUT _jn_ipo_error LANGUAGES CXX)
    if(NOT _jn_ipo_supported)
        if(JNATIVE_IPO STREQUAL "ON")
            message(FATAL_ERROR "Requested jNative release IPO is unavailable: ${_jn_ipo_error}")
        endif()
        message(STATUS "jNative release IPO unavailable; using ordinary optimization: ${_jn_ipo_error}")
    endif()
endif()
foreach(_target IN LISTS _jn_compiled_targets)
    set_target_properties(${_target} PROPERTIES
        INTERPROCEDURAL_OPTIMIZATION_DEBUG FALSE
        INTERPROCEDURAL_OPTIMIZATION_RELEASE ${_jn_ipo_supported}
        INTERPROCEDURAL_OPTIMIZATION_RELWITHDEBINFO ${_jn_ipo_supported}
        INTERPROCEDURAL_OPTIMIZATION_MINSIZEREL ${_jn_ipo_supported})
endforeach()
message(STATUS "jNative release IPO: ${_jn_ipo_supported} (requested ${JNATIVE_IPO})")
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/jnative-optimization.properties"
    "ipo.requested=${JNATIVE_IPO}\nipo.enabled=${_jn_ipo_supported}\nipo.configurations=Release,RelWithDebInfo,MinSizeRel\n")

target_link_libraries(jnative_app PUBLIC jnative_runtime)
# Different configurations may intentionally publish the same distribution path.
# Relink/archive on each requested build so a newer file from another toolchain
# cannot make this configuration appear up to date. No application code executes.
set(_jn_stamp "${CMAKE_CURRENT_BINARY_DIR}/jnative_configuration.cpp")
file(WRITE "${_jn_stamp}" "// Link this configuration's objects into the selected output.\n")
add_custom_target(jnative_link_configuration
    COMMAND "${CMAKE_COMMAND}" -E touch "${_jn_stamp}" VERBATIM)
target_sources(jnative_app PRIVATE "${_jn_stamp}")
add_dependencies(jnative_app jnative_link_configuration)
target_include_directories(jnative_app PUBLIC "${JNATIVE_SOURCE_DIRECTORY}" "${CMAKE_CURRENT_SOURCE_DIR}/user")
set_target_properties(jnative_app PROPERTIES OUTPUT_NAME "${JNATIVE_TARGET_NAME}")
# Runtime archives are implementation artifacts of this exact configuration.
# Keep them away from another toolchain/configuration's distribution directory.
set_target_properties(jnative_runtime jnative_platform PROPERTIES
    ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/lib/$<CONFIG>")
foreach(_configuration Debug Release RelWithDebInfo MinSizeRel)
    string(TOUPPER "${_configuration}" _upper)
    set_target_properties(jnative_runtime jnative_platform PROPERTIES
        ARCHIVE_OUTPUT_DIRECTORY_${_upper} "${CMAKE_CURRENT_BINARY_DIR}/lib/${_configuration}")
endforeach()
foreach(_kind RUNTIME LIBRARY ARCHIVE)
    if(NOT DEFINED CMAKE_${_kind}_OUTPUT_DIRECTORY)
        set_target_properties(jnative_app PROPERTIES
            ${_kind}_OUTPUT_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/$<LOWER_CASE:$<CONFIG>>")
    endif()
endforeach()
option(JNATIVE_MSVC_AGGRESSIVE_INLINING "Use stronger MSVC inlining in Release and RelWithDebInfo" ON)
foreach(_target IN LISTS _jn_compiled_targets)
    if(MSVC)
        # Native imports can throw C++ exceptions even when their ABI uses C linkage.
        target_compile_options(${_target} PRIVATE "$<$<COMPILE_LANGUAGE:CXX>:/fp:strict;/utf-8;/EHsc->")
        if(JNATIVE_MSVC_AGGRESSIVE_INLINING AND CMAKE_CXX_COMPILER_ID STREQUAL "MSVC"
                AND MSVC_VERSION GREATER_EQUAL 1920)
            # Keep Debug and size-oriented builds at the toolchain's default.
            # Disable this option to supply a different inlining policy yourself.
            target_compile_options(${_target} PRIVATE
                "$<$<AND:$<COMPILE_LANGUAGE:CXX>,$<CONFIG:Release,RelWithDebInfo>>:/Ob3>")
        endif()
    else()
        target_compile_options(${_target} PRIVATE -fno-fast-math -ffp-contract=off)
    endif()
endforeach()
if(MINGW)
    target_link_options(jnative_app PRIVATE -static-libgcc -static-libstdc++)
endif()
add_library(jNative::Runtime ALIAS jnative_runtime)
add_library(jNative::Platform ALIAS jnative_platform)
if(NOT JNATIVE_OUTPUT_KIND STREQUAL "EXECUTABLE")
    add_library(jNative::Application ALIAS jnative_app)
endif()
include("${CMAKE_CURRENT_SOURCE_DIR}/user/CMakeLists.txt" OPTIONAL)
include("${_jn_runtime}/jn_zlib.cmake")
include("${_jn_runtime}/jn_diagnostics.cmake")
if(JNATIVE_OUTPUT_KIND STREQUAL "SHARED_LIBRARY" OR (JNATIVE_OUTPUT_KIND STREQUAL "EXECUTABLE"
        AND NOT JNATIVE_NATIVE_TRACES AND NOT JNATIVE_CRASH_REPORTS AND JNATIVE_SYMBOLS STREQUAL "NONE"))
    file(GENERATE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/jn_deploy_$<CONFIG>.cmake" CONTENT
"set(CMAKE_CXX_COMPILER_ID [==[${CMAKE_CXX_COMPILER_ID}]==])
set(JNATIVE_RUNTIME_LIBRARY_DIRECTORIES [==[${JNATIVE_RUNTIME_LIBRARY_DIRECTORIES}]==])
include([==[${_jn_runtime}/jn_dependencies.cmake]==])
jn_copy_runtime_dependencies([==[$<TARGET_FILE:jnative_app>]==] ${JNATIVE_OUTPUT_KIND} [==[${CMAKE_SYSTEM_NAME}]==] [==[${CMAKE_OBJDUMP}]==] files)
set(manifest [==[${CMAKE_CURRENT_BINARY_DIR}/jnative-dependencies-$<CONFIG>.properties]==])
file(WRITE \"\${manifest}\" \"\")
set(index 0)
foreach(path IN LISTS files)
    file(APPEND \"\${manifest}\" \"file.\${index}=\${path}\\n\")
    math(EXPR index \"\${index}+1\")
endforeach()
")
    add_custom_command(TARGET jnative_app POST_BUILD
        COMMAND "${CMAKE_COMMAND}" -P "${CMAKE_CURRENT_BINARY_DIR}/jn_deploy_$<CONFIG>.cmake" VERBATIM)
endif()
# A custom build target must actually finish this configuration's application;
# an executable left by a previous build cannot satisfy a new compilation request.
string(RANDOM LENGTH 32 ALPHABET 0123456789abcdef _jn_request)
file(GENERATE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/jn_complete_$<CONFIG>.cmake" CONTENT
    "file(WRITE [==[${CMAKE_CURRENT_BINARY_DIR}/jnative-completed-$<CONFIG>.txt]==] [==[${_jn_request}]==])\n")
add_custom_command(TARGET jnative_app POST_BUILD
    COMMAND "${CMAKE_COMMAND}" -P "${CMAKE_CURRENT_BINARY_DIR}/jn_complete_$<CONFIG>.cmake" VERBATIM)
file(GENERATE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/jnative-artifact-$<CONFIG>.properties" CONTENT
    "kind=${JNATIVE_OUTPUT_KIND}\npath=$<TARGET_FILE:jnative_app>\nbuild.directory=${CMAKE_CURRENT_BINARY_DIR}\nruntime=$<TARGET_FILE:jnative_runtime>\nplatform=$<TARGET_FILE:jnative_platform>\nrequest=${_jn_request}\n")
