if(NOT STORE)
    message(FATAL_ERROR "JNATIVE_ARCHIVE_STORE must name a permanent private archive directory")
endif()
get_filename_component(store "${STORE}" ABSOLUTE)
file(REAL_PATH "${PROJECT}" project)
file(READ "${project}/jnative-project.properties" properties)
if(properties MATCHES "(^|\n)mode=editable(\n|$)")
    set(build_root "${project}")
else()
    get_filename_component(build_root "${project}" DIRECTORY)
endif()
file(MAKE_DIRECTORY "${store}")
file(REAL_PATH "${store}" store)
cmake_path(IS_PREFIX build_root "${store}" NORMALIZE disposable)
if(disposable)
    message(FATAL_ERROR "Permanent archive must be outside the owning build output")
endif()
if(NOT CONFIG)
    set(CONFIG Release)
endif()
if(REQUIRE_RELEASE AND NOT CONFIG STREQUAL "Release")
    message(FATAL_ERROR "jnative_release requires the Release configuration")
endif()
file(READ "${project}/diagnostics/latest-${CONFIG}.txt" id)
string(STRIP "${id}" id)
string(LENGTH "${id}" length)
if(NOT id MATCHES "^[0-9a-f]+$" OR NOT length EQUAL 32)
    message(FATAL_ERROR "Invalid archive identity")
endif()
set(source "${project}/diagnostics/${id}")
file(READ "${source}/manifest.json" manifest)
string(JSON count LENGTH "${manifest}" files)
if(count LESS 1 OR count GREATER 100000)
    message(FATAL_ERROR "Invalid archive inventory")
endif()
math(EXPR end "${count}-1")
function(jn_verify directory)
    foreach(index RANGE ${end})
        string(JSON name MEMBER "${manifest}" files ${index})
        string(JSON expected GET "${manifest}" files "${name}")
        string(LENGTH "${directory}/${name}" path_length)
        if(path_length GREATER 220)
            message(FATAL_ERROR "JN4010 Private archive path exceeds the portable budget: ${directory}/${name}")
        endif()
        cmake_path(ABSOLUTE_PATH name BASE_DIRECTORY "${directory}" NORMALIZE OUTPUT_VARIABLE file)
        cmake_path(IS_PREFIX directory "${file}" NORMALIZE inside)
        if(NOT inside OR IS_SYMLINK "${file}")
            message(FATAL_ERROR "Invalid archive path: ${name}")
        endif()
        file(REAL_PATH "${file}" actual_path)
        cmake_path(IS_PREFIX directory "${actual_path}" NORMALIZE inside)
        if(NOT inside)
            message(FATAL_ERROR "Archive file resolves outside its directory")
        endif()
        file(SHA256 "${file}" actual)
        if(NOT actual STREQUAL expected)
            message(FATAL_ERROR "Diagnostic artifact checksum mismatch: ${name}")
        endif()
    endforeach()
endfunction()
jn_verify("${source}")
if(EXISTS "${store}/${id}")
    file(READ "${store}/${id}/manifest.json" existing)
    if(NOT existing STREQUAL manifest)
        message(FATAL_ERROR "Archive identity conflict")
    endif()
else()
    string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef nonce)
    set(stage "${store}/.jnative-stage-${nonce}")
    file(MAKE_DIRECTORY "${stage}")
    foreach(index RANGE ${end})
        string(JSON name MEMBER "${manifest}" files ${index})
        configure_file("${source}/${name}" "${stage}/${name}" COPYONLY)
    endforeach()
    configure_file("${source}/manifest.json" "${stage}/manifest.json" COPYONLY)
    jn_verify("${stage}")
    file(RENAME "${stage}" "${store}/${id}")
endif()
jn_verify("${store}/${id}")
message(STATUS "Verified permanent archive: ${store}/${id}")
