if(NOT JNATIVE_NEEDS_ZLIB)
    return()
endif()
if(NOT TARGET ZLIB::ZLIB AND NOT TARGET ZLIB::ZLIBSTATIC)
    find_package(ZLIB QUIET)
endif()
if(NOT TARGET ZLIB::ZLIB AND NOT TARGET ZLIB::ZLIBSTATIC)
    include(FetchContent)
    set(ZLIB_BUILD_TESTING OFF CACHE BOOL "" FORCE)
    set(ZLIB_BUILD_SHARED OFF CACHE BOOL "" FORCE)
    set(ZLIB_BUILD_STATIC ON CACHE BOOL "" FORCE)
    set(ZLIB_INSTALL OFF CACHE BOOL "" FORCE)
    FetchContent_Declare(jnative_zlib
        URL https://zlib.net/zlib-1.3.2.tar.gz
        URL_HASH SHA256=bb329a0a2cd0274d05519d61c667c062e06990d72e125ee2dfa8de64f0119d16)
    FetchContent_MakeAvailable(jnative_zlib)
endif()
if(TARGET ZLIB::ZLIBSTATIC)
    target_link_libraries(jnative_runtime PUBLIC ZLIB::ZLIBSTATIC)
else()
    target_link_libraries(jnative_runtime PUBLIC ZLIB::ZLIB)
endif()
target_compile_definitions(jnative_runtime PRIVATE JNATIVE_USE_ZLIB=1)
